# Generated by Django 2.0.5 on 2018-10-06 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('login_time', models.DateTimeField(null=True)),
                ('username', models.CharField(max_length=64)),
                ('nickname', models.CharField(default='暂无昵称', max_length=64)),
                ('password', models.CharField(max_length=512)),
                ('raw_password', models.CharField(max_length=512)),
                ('intro', models.CharField(default='暂无简介', max_length=256)),
                ('phone', models.CharField(default='暂无手机号', max_length=32)),
                ('email', models.CharField(default='暂无邮箱', max_length=265)),
                ('is_activated', models.BooleanField(default=False)),
            ],
        ),
    ]
