# Generated by Django 2.0.5 on 2018-11-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ua', '0003_auto_20181009_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='idcode_time',
            new_name='verify_code_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='idcode',
        ),
        migrations.AddField(
            model_name='user',
            name='verify_op',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='verify_st',
            field=models.CharField(default='-1', max_length=10),
        ),
    ]
