# Generated by Django 2.0.5 on 2018-12-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ua', '0004_auto_20181105_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idcode_time',
            field=models.DateTimeField(null=True),
        ),
    ]
