# Generated by Django 2.0.5 on 2018-12-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ua', '0005_user_idcode_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
