# Generated by Django 2.0.5 on 2018-12-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ua', '0007_user_active_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='idcode_time',
        ),
        migrations.AlterField(
            model_name='user',
            name='verify_code_time',
            field=models.DateTimeField(null=True),
        ),
    ]
